import { Fragment, useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import maplibregl from "maplibre-gl";
import bbox from "@turf/bbox";
import areaInterest from "../mock-data/area-interest";
import resultCovjson from "../mock-data/result-covjson";
import covJson2GeoJSON from "../lib/covjson2geojson";

const Home: NextPage = () => {
  useEffect(() => {
    const map = new maplibregl.Map({
      container: "map",
      hash: true,
      style:
        "https://cloud.vallarismaps.com/core/api/styles/1.0-beta/styles/62174cf1f934f778c9c27013?api_key=8pM6VWiF0CUnQxVTX1HwnZdNCNn4b8gDaMvlc7WpvqlyIF4xSclZQr9mhacIcAcr",
    });
    map.on("load", () => {
      map.addLayer({
        id: "parcel",
        type: "line",
        source: { type: "geojson", data: areaInterest },
        layout: {
          "line-join": "round",
          "line-cap": "round",
        },
        paint: {
          "line-color": "#888",
          "line-width": 1,
        },
      });
      const geojsonResult = covJson2GeoJSON(resultCovjson);

      map.fitBounds(bbox(geojsonResult));
      map.addSource("covGrid", { type: "geojson", data: geojsonResult });
      map.addLayer(
        {
          id: "covGrid",
          type: "fill",
          source: "covGrid",
          filter: ["!=", ["get", "volume"], null],
          // layout: {
          //   "line-join": "round",
          //   "line-cap": "round",
          // },
          paint: {
            "fill-color": [
              "interpolate",
              ["linear"],
              ["get", "volume"],
              -0.37,
              ["to-color", "rgb(221, 234, 246)"],
              0.29,
              ["to-color", "rgb(49, 130, 189)"],
            ],
          },
        },
        "parcel"
      );
    });

    return () => {
      map.remove();
    };
  }, []);

  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        id="map"
        className={"h-full w-full"}
        style={{ height: "100vh", backgroundColor: "#fff" }}
      ></main>
    </Fragment>
  );
};

export default Home;
